services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: F1 Lightning McQueen
      POSTGRES_PASSWORD: F1 Lightning McQueen
      POSTGRES_DB: F1 Lightning McQueen
    ports:
      - "5433:5432"
    volumes:
      - F1 Lightning McQueen_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U F1 Lightning McQueen -d F1 Lightning McQueen"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql+psycopg://F1 Lightning McQueen:F1 Lightning McQueen@postgres:5432/F1 Lightning McQueen
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app

volumes:
  F1 Lightning McQueen_postgres_data:
