"""add raw column to intervals

Revision ID: 17e03cf7cd32
Revises: f997c149056a
Create Date: 2026-08-16 16:44:49.291896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17e03cf7cd32'
down_revision: Union[str, None] = 'f997c149056a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervals', sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intervals', 'raw')
    # ### end Alembic commands ###
