"""key drivers by full_name instead of driver_number

Revision ID: f145802a3434
Revises: 17e03cf7cd32
Create Date: 2026-08-16 21:11:58.703420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f145802a3434'
down_revision: Union[str, None] = '17e03cf7cd32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_drivers_driver_number', table_name='drivers')
    op.create_index(op.f('ix_drivers_driver_number'), 'drivers', ['driver_number'], unique=False)
    op.create_index(op.f('ix_drivers_full_name'), 'drivers', ['full_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drivers_full_name'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_driver_number'), table_name='drivers')
    op.create_index('ix_drivers_driver_number', 'drivers', ['driver_number'], unique=True)
    # ### end Alembic commands ###
