"""initial schema

Revision ID: f997c149056a
Revises: 
Create Date: 2026-08-16 16:19:31.154285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f997c149056a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_key', sa.Integer(), nullable=False),
    sa.Column('circuit_short_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('country_name', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuits_circuit_key'), 'circuits', ['circuit_key'], unique=True)
    op.create_table('constructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_acronym', sa.String(), nullable=True),
    sa.Column('team_colour', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constructors_name'), 'constructors', ['name'], unique=True)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('name_acronym', sa.String(), nullable=True),
    sa.Column('broadcast_name', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('headshot_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_driver_number'), 'drivers', ['driver_number'], unique=True)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_year'), 'seasons', ['year'], unique=True)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_key', sa.Integer(), nullable=False),
    sa.Column('meeting_name', sa.String(), nullable=False),
    sa.Column('meeting_official_name', sa.String(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('gmt_offset', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_circuit_id'), 'meetings', ['circuit_id'], unique=False)
    op.create_index(op.f('ix_meetings_meeting_key'), 'meetings', ['meeting_key'], unique=True)
    op.create_index(op.f('ix_meetings_season_id'), 'meetings', ['season_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('gmt_offset', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_meeting_id'), 'sessions', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_sessions_session_key'), 'sessions', ['session_key'], unique=True)
    op.create_table('intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('gap_to_leader', sa.Float(), nullable=True),
    sa.Column('interval', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_id', 'date', name='uq_intervals_session_driver_date')
    )
    op.create_index(op.f('ix_intervals_driver_id'), 'intervals', ['driver_id'], unique=False)
    op.create_index(op.f('ix_intervals_session_id'), 'intervals', ['session_id'], unique=False)
    op.create_table('laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('lap_duration', sa.Float(), nullable=True),
    sa.Column('duration_sector_1', sa.Float(), nullable=True),
    sa.Column('duration_sector_2', sa.Float(), nullable=True),
    sa.Column('duration_sector_3', sa.Float(), nullable=True),
    sa.Column('is_pit_out_lap', sa.Boolean(), nullable=True),
    sa.Column('i1_speed', sa.Float(), nullable=True),
    sa.Column('i2_speed', sa.Float(), nullable=True),
    sa.Column('st_speed', sa.Float(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_id', 'lap_number', name='uq_laps_session_driver_lap')
    )
    op.create_index(op.f('ix_laps_driver_id'), 'laps', ['driver_id'], unique=False)
    op.create_index(op.f('ix_laps_session_id'), 'laps', ['session_id'], unique=False)
    op.create_table('pit_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('pit_duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_id', 'lap_number', name='uq_pit_stops_session_driver_lap')
    )
    op.create_index(op.f('ix_pit_stops_driver_id'), 'pit_stops', ['driver_id'], unique=False)
    op.create_index(op.f('ix_pit_stops_session_id'), 'pit_stops', ['session_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_id', 'date', name='uq_positions_session_driver_date')
    )
    op.create_index(op.f('ix_positions_driver_id'), 'positions', ['driver_id'], unique=False)
    op.create_index(op.f('ix_positions_session_id'), 'positions', ['session_id'], unique=False)
    op.create_table('race_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('lap_number', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('sector', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'date', 'category', 'message', name='uq_race_control_session_date_category_message')
    )
    op.create_index(op.f('ix_race_control_driver_id'), 'race_control', ['driver_id'], unique=False)
    op.create_index(op.f('ix_race_control_session_id'), 'race_control', ['session_id'], unique=False)
    op.create_table('session_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('team_colour', sa.String(), nullable=True),
    sa.Column('headshot_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_id', name='uq_session_entries_session_driver')
    )
    op.create_index(op.f('ix_session_entries_constructor_id'), 'session_entries', ['constructor_id'], unique=False)
    op.create_index(op.f('ix_session_entries_driver_id'), 'session_entries', ['driver_id'], unique=False)
    op.create_index(op.f('ix_session_entries_session_id'), 'session_entries', ['session_id'], unique=False)
    op.create_table('session_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('number_of_laps', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('dnf', sa.Boolean(), nullable=True),
    sa.Column('dns', sa.Boolean(), nullable=True),
    sa.Column('dsq', sa.Boolean(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('gap_to_leader', sa.String(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_id', name='uq_session_results_session_driver')
    )
    op.create_index(op.f('ix_session_results_driver_id'), 'session_results', ['driver_id'], unique=False)
    op.create_index(op.f('ix_session_results_session_id'), 'session_results', ['session_id'], unique=False)
    op.create_table('stints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('stint_number', sa.Integer(), nullable=False),
    sa.Column('lap_start', sa.Integer(), nullable=True),
    sa.Column('lap_end', sa.Integer(), nullable=True),
    sa.Column('compound', sa.String(), nullable=True),
    sa.Column('tyre_age_at_start', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_id', 'stint_number', name='uq_stints_session_driver_stint')
    )
    op.create_index(op.f('ix_stints_driver_id'), 'stints', ['driver_id'], unique=False)
    op.create_index(op.f('ix_stints_session_id'), 'stints', ['session_id'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('air_temperature', sa.Float(), nullable=True),
    sa.Column('track_temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'date', name='uq_weather_session_date')
    )
    op.create_index(op.f('ix_weather_session_id'), 'weather', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_session_id'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_stints_session_id'), table_name='stints')
    op.drop_index(op.f('ix_stints_driver_id'), table_name='stints')
    op.drop_table('stints')
    op.drop_index(op.f('ix_session_results_session_id'), table_name='session_results')
    op.drop_index(op.f('ix_session_results_driver_id'), table_name='session_results')
    op.drop_table('session_results')
    op.drop_index(op.f('ix_session_entries_session_id'), table_name='session_entries')
    op.drop_index(op.f('ix_session_entries_driver_id'), table_name='session_entries')
    op.drop_index(op.f('ix_session_entries_constructor_id'), table_name='session_entries')
    op.drop_table('session_entries')
    op.drop_index(op.f('ix_race_control_session_id'), table_name='race_control')
    op.drop_index(op.f('ix_race_control_driver_id'), table_name='race_control')
    op.drop_table('race_control')
    op.drop_index(op.f('ix_positions_session_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_driver_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_pit_stops_session_id'), table_name='pit_stops')
    op.drop_index(op.f('ix_pit_stops_driver_id'), table_name='pit_stops')
    op.drop_table('pit_stops')
    op.drop_index(op.f('ix_laps_session_id'), table_name='laps')
    op.drop_index(op.f('ix_laps_driver_id'), table_name='laps')
    op.drop_table('laps')
    op.drop_index(op.f('ix_intervals_session_id'), table_name='intervals')
    op.drop_index(op.f('ix_intervals_driver_id'), table_name='intervals')
    op.drop_table('intervals')
    op.drop_index(op.f('ix_sessions_session_key'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_meeting_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_meetings_season_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_key'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_circuit_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_seasons_year'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_drivers_driver_number'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_constructors_name'), table_name='constructors')
    op.drop_table('constructors')
    op.drop_index(op.f('ix_circuits_circuit_key'), table_name='circuits')
    op.drop_table('circuits')
    # ### end Alembic commands ###
